id: P010601
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:59.501393
source_metadata:
  id: bdr:W3CN2116
  title: ལི་ཐང་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    5e63418267d94a8db78c80f7f0c20ca7:
      image_group_id: I3CN2118
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
